student_count = 16
# first we print the list of students
puts "The students of my cohort at Makers Academy"
puts "-------------"
puts "Sanda"
puts "Huy"
puts "Stephi"
puts "David"
puts "Emily"
puts "Kieran"
puts "Richard"
puts "Jacob"
puts "Marcin"
puts "Gabe"
puts "Hannah"
puts "Bibiana"
puts "Chris"
puts "Ptolemy"
puts "Luke"
puts "Danielle"
# finally, we print the total
puts "Overall we have #{student_count} great students"