puts "The students of my cohort at Makers Academy"
puts "-------------"
puts "Sanda"
puts "Huy"
puts "Stephi"
puts "David"
puts "Emily"
puts "Kieran"
puts "Richard"
puts "Jacob"
puts "Marcin"
puts "Gabe"
puts "Hannah"
puts "Bibiana"
puts "Chris"
puts "Ptolemy"
puts "Luke"
puts "Danielle"
print "Overall we have "
print 16
puts " great students"